version: "3.7"

services:
  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - 80:80
      - 443:443
      - 2019:2019
    volumes:
      - "/etc/caddy/init.json:/init.json"
      - "caddy:/config"
      - "caddy:/data"
      - "/var/www:/var/www"
    logging:
      options:
        max-size: "10k"
        max-file: "5"
    command: ["caddy", "run", "--config", "/init.json", "--resume"]
    networks:
      - default
      - proxy
volumes:
  caddy:
networks:
  proxy:
    external: true
